# Generated by Django 4.1.3 on 2022-11-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logged_time',
            name='Log',
            field=models.ManyToManyField(related_name='login_status', to='Ems.log_status'),
        ),
    ]
