# Generated by Django 4.1.3 on 2022-11-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_status',
            old_name='Name',
            new_name='Log',
        ),
    ]
