# Generated by Django 4.1.3 on 2022-11-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ems', '0002_rename_name_log_status_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_status',
            name='Log',
            field=models.CharField(choices=[('login', 'login'), ('logout', 'logout'), ('break', 'break'), ('back to work', 'back to work')], max_length=30),
        ),
    ]
